/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todoz.java;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Dawid
 */
public class Todo extends javax.swing.JFrame {
    public String tytul;
    public String opis;
    
    
    DefaultListModel<String> dlm = new  DefaultListModel<String>();
    DefaultListModel<String> dlm2 = new  DefaultListModel<String>();
    public Todo() {
        initComponents();
        
        zadania = new File("zadania.txt");
        opisZ = new File("opisZ.txt");
        
        jDDodawanie.setLocationRelativeTo(null);
        jDUstawienia.setLocationRelativeTo(null);
        jMod.setLocationRelativeTo(null);
        setLocationRelativeTo(null);
        
        BufferedReader br = null;
        
        try{
        br = new BufferedReader(new FileReader("zadania.txt"));
        String line;
        while ((line = br.readLine()) != null) {
            dlm.addElement(line);
        }
        jZadania.setModel(dlm);
        jTitle.setModel(dlm);
         }
        catch(Exception e){
            System.out.println("");
        }
        
        try{
        br = new BufferedReader(new FileReader("opisZ.txt"));
        String line;
        while ((line = br.readLine()) != null) {
            dlm2.addElement(line);
        }
        jZOpis.setModel(dlm2);
        
         }
        catch(Exception e){
            System.out.println("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDDodawanie = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTytul = new javax.swing.JTextField();
        jDDodaj = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jOpis = new javax.swing.JTextArea();
        jAnuluj = new javax.swing.JButton();
        jDUstawienia = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRJasny = new javax.swing.JRadioButton();
        jRciemny = new javax.swing.JRadioButton();
        jOk = new javax.swing.JButton();
        jUAnuluj = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMod = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTitle = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jZOpis = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jMOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDodaj = new javax.swing.JButton();
        jUsun = new javax.swing.JButton();
        jModyfikuj = new javax.swing.JButton();
        jZamknij = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jZadania = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jZapisz = new javax.swing.JButton();
        jUstawienia = new javax.swing.JButton();

        jDDodawanie.setMinimumSize(new java.awt.Dimension(350, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(330, 260));

        jLabel1.setText("Zadanie:");

        jDDodaj.setBackground(new java.awt.Color(0, 204, 0));
        jDDodaj.setText("Dodaj");
        jDDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDDodajActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Opis:");

        jOpis.setColumns(20);
        jOpis.setRows(5);
        jScrollPane2.setViewportView(jOpis);

        jAnuluj.setBackground(new java.awt.Color(204, 0, 0));
        jAnuluj.setText("Anuluj");
        jAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnulujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jAnuluj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDDodaj))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTytul, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTytul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDDodaj)
                    .addComponent(jAnuluj))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jDDodawanieLayout = new javax.swing.GroupLayout(jDDodawanie.getContentPane());
        jDDodawanie.getContentPane().setLayout(jDDodawanieLayout);
        jDDodawanieLayout.setHorizontalGroup(
            jDDodawanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jDDodawanieLayout.setVerticalGroup(
            jDDodawanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jDUstawienia.setMinimumSize(new java.awt.Dimension(300, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Wybierz motyw:");

        jRJasny.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRJasny);
        jRJasny.setSelected(true);
        jRJasny.setText("Jasny");

        jRciemny.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRciemny);
        jRciemny.setText("Ciemny");

        jOk.setBackground(new java.awt.Color(0, 255, 0));
        jOk.setText("OK");
        jOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkActionPerformed(evt);
            }
        });

        jUAnuluj.setBackground(new java.awt.Color(204, 0, 51));
        jUAnuluj.setText("Anuluj");
        jUAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUAnulujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jRJasny)
                        .addGap(34, 34, 34)
                        .addComponent(jRciemny)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jUAnuluj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRJasny)
                    .addComponent(jRciemny))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOk)
                    .addComponent(jUAnuluj))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDUstawieniaLayout = new javax.swing.GroupLayout(jDUstawienia.getContentPane());
        jDUstawienia.getContentPane().setLayout(jDUstawieniaLayout);
        jDUstawieniaLayout.setHorizontalGroup(
            jDUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDUstawieniaLayout.setVerticalGroup(
            jDUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMod.setMinimumSize(new java.awt.Dimension(415, 275));
        jMod.setPreferredSize(new java.awt.Dimension(415, 275));
        jMod.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(401, 304));
        jPanel4.setPreferredSize(new java.awt.Dimension(401, 254));

        jScrollPane3.setViewportView(jTitle);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tytuł");

        jScrollPane4.setViewportView(jZOpis);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Opis");

        jMOK.setBackground(new java.awt.Color(255, 0, 0));
        jMOK.setText("Zamknij");
        jMOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jMOK)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jMOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jModLayout = new javax.swing.GroupLayout(jMod.getContentPane());
        jMod.getContentPane().setLayout(jModLayout);
        jModLayout.setHorizontalGroup(
            jModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jModLayout.setVerticalGroup(
            jModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jDodaj.setBackground(new java.awt.Color(0, 204, 0));
        jDodaj.setText("Dodaj");
        jDodaj.setMaximumSize(new java.awt.Dimension(87, 25));
        jDodaj.setMinimumSize(new java.awt.Dimension(87, 25));
        jDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajActionPerformed(evt);
            }
        });

        jUsun.setBackground(new java.awt.Color(204, 0, 0));
        jUsun.setText("Usuń");
        jUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsunActionPerformed(evt);
            }
        });

        jModyfikuj.setBackground(new java.awt.Color(255, 204, 0));
        jModyfikuj.setText("Wyświetl");
        jModyfikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModyfikujActionPerformed(evt);
            }
        });

        jZamknij.setBackground(new java.awt.Color(255, 0, 102));
        jZamknij.setText("Zamknij");
        jZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZamknijActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jZadania);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Notatki");

        jZapisz.setBackground(new java.awt.Color(0, 51, 255));
        jZapisz.setText("Zapisz");
        jZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZapiszActionPerformed(evt);
            }
        });

        jUstawienia.setBackground(new java.awt.Color(51, 153, 255));
        jUstawienia.setText("Ustawienia");
        jUstawienia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUstawieniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jZamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jModyfikuj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jUstawienia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUstawienia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jModyfikuj, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jZamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajActionPerformed
        jDDodawanie.setVisible(true);
        jTytul.setText("");
        jOpis.setText("");
        
    }//GEN-LAST:event_jDodajActionPerformed

    private void jDDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDDodajActionPerformed
     
        opis = jOpis.getText();
        tytul = jTytul.getText();
        
        jZOpis.setModel(dlm2);
        jTitle.setModel(dlm);
        jZadania.setModel(dlm);
        
  
        
        dlm.addElement(tytul);
        dlm2.addElement(opis);
        jDDodawanie.setVisible(false);
    }//GEN-LAST:event_jDDodajActionPerformed

    private void jZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jZamknijActionPerformed

    private void jUstawieniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUstawieniaActionPerformed
        jDUstawienia.setVisible(true);
    }//GEN-LAST:event_jUstawieniaActionPerformed

    private void jAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnulujActionPerformed
        jDDodawanie.setVisible(false);
    }//GEN-LAST:event_jAnulujActionPerformed

    private void jOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkActionPerformed
        if(jRJasny.isSelected()){
            jPanel1.setBackground(Color.WHITE);
            jPanel2.setBackground(Color.WHITE);
            jPanel3.setBackground(Color.WHITE);
            jPanel4.setBackground(Color.WHITE);
            jLabel2.setForeground(Color.BLACK);
            jLabel1.setForeground(Color.BLACK);
            jLabel3.setForeground(Color.BLACK);
            jLabel4.setForeground(Color.BLACK);
            jRJasny.setForeground(Color.BLACK);
            jRciemny.setForeground(Color.BLACK);
            jLabel5.setForeground(Color.BLACK);
            jLabel6.setForeground(Color.BLACK);
            jDUstawienia.setVisible(false);
        }
        if(jRciemny.isSelected()){
            jPanel1.setBackground(Color.BLACK);
            jPanel2.setBackground(Color.BLACK);
            jPanel3.setBackground(Color.BLACK);
            jPanel4.setBackground(Color.BLACK);
            jLabel2.setForeground(Color.WHITE);
            jLabel1.setForeground(Color.WHITE);
            jLabel3.setForeground(Color.WHITE);
            jLabel4.setForeground(Color.WHITE);
            jRJasny.setForeground(Color.WHITE);
            jRciemny.setForeground(Color.WHITE);
            jLabel5.setForeground(Color.WHITE);
            jLabel6.setForeground(Color.WHITE);
            jDUstawienia.setVisible(false);
        }
        
    }//GEN-LAST:event_jOkActionPerformed

    private void jUAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUAnulujActionPerformed
        jDUstawienia.setVisible(false);
    }//GEN-LAST:event_jUAnulujActionPerformed

    private void jModyfikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModyfikujActionPerformed
        jMod.setVisible(true);
    }//GEN-LAST:event_jModyfikujActionPerformed

    private void jUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsunActionPerformed
        int index = jZadania.getSelectedIndex();
        dlm.removeElementAt(index);
        dlm2.removeElementAt(index);
    }//GEN-LAST:event_jUsunActionPerformed

    private void jZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZapiszActionPerformed
    try {                                                                  
        FileWriter fw = new FileWriter(zadania); 
        for (int i=0; i<jTitle.getModel().getSize(); i++){                             
        fw.write(jTitle.getModel().getElementAt(i)+"\n");                                                   
        }                                                                  
        fw.close();                                                         
    } catch (IOException ex) {                                              
        Logger.getLogger(Todo.class.getName()).log(Level.SEVERE, null, ex); 
    }  
    
    try {                                                                  
        FileWriter fw = new FileWriter(opisZ); 
        for (int i=0; i<jZOpis.getModel().getSize(); i++){                             
        fw.write(jZOpis.getModel().getElementAt(i)+"\n");                                                   
        }                                                                  
        fw.close();                                                         
    } catch (IOException ex) {                                              
        Logger.getLogger(Todo.class.getName()).log(Level.SEVERE, null, ex); 
    } 
    }//GEN-LAST:event_jZapiszActionPerformed

    private void jMOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMOKActionPerformed
        
        jMod.setVisible(false);
    }//GEN-LAST:event_jMOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Todo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Todo().setVisible(true);
            }
        });
    }
    private File opisZ;
    private File zadania;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAnuluj;
    private javax.swing.JButton jDDodaj;
    private javax.swing.JDialog jDDodawanie;
    private javax.swing.JDialog jDUstawienia;
    private javax.swing.JButton jDodaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jMOK;
    private javax.swing.JDialog jMod;
    private javax.swing.JButton jModyfikuj;
    private javax.swing.JButton jOk;
    private javax.swing.JTextArea jOpis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRJasny;
    private javax.swing.JRadioButton jRciemny;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> jTitle;
    private javax.swing.JTextField jTytul;
    private javax.swing.JButton jUAnuluj;
    private javax.swing.JButton jUstawienia;
    private javax.swing.JButton jUsun;
    private javax.swing.JList<String> jZOpis;
    private javax.swing.JList<String> jZadania;
    private javax.swing.JButton jZamknij;
    private javax.swing.JButton jZapisz;
    // End of variables declaration//GEN-END:variables
}
